### ISSUE TITLE
Analog drum input support

### ISSUE THREAD

**Issue by ShikyC** [BroGamer4256/TaikoArcadeLoader#5]
Hi I'm planning to add analog output to my USB taiko drum so that it can simulate the force as close to an arcade drum as possible.  Currently my drum controller simulates as a keyboard but I'm refactoring it into a HID device (like an analog joystick) that can communicate with the game directly. I'm wondering if it's possible to add custom analog HID input support other than keyboards?

**Comment by vixen256** [comment]
Yes, anything that is compatible with SDL will work fine

**Comment by ShikyC** [comment]
~~Yes but as I see in the code all the analog input are turned to 0 and 1 boolean values instead of raw analog values.~~

I found this issue had been resolved in the `Refactor` branch. Thanks!
